server:
  port: 8888
  
spring:
  application:
    name: vxml-server-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VictoryPark10/SpringConfigServer-test
          default-label: main
